browser=chrome
base.url=https://demoqa.com
form.url=https://demoqa.com/automation-practice-form
table.url=https://demoqa.com/webtables
alert.url=https://demoqa.com/alerts
frame.url=https://demoqa.com/frames
widget.url=https://demoqa.com/date-picker
accordion.url=https://demoqa.com/accordian
timeout=10